"""Phase 4 figure regeneration entry point.

Figures are generated by the country and measurement functions so their figure
data, PNG, and PDF artifacts remain aligned with the descriptive tables.
"""
from phase4_common import fies_quality, kazakhstan_outputs, kyrgyzstan_outputs, load_data, missingness, setup_logging, uzbekistan_outputs

if __name__ == "__main__":
    setup_logging()
    data = load_data()
    missingness(data)
    fies_quality(data)
    kyrgyzstan_outputs(data)
    uzbekistan_outputs(data)
    kazakhstan_outputs(data)
